package com.archos.mediacenter.video.player;
import android.app.*;
import android.view.*;
import android.widget.*;
import com.archos.mediacenter.video.leanback.*;
import com.archos.mediacenter.video.browser.adapters.object.*;
final class PreviewPlaybackInfo {
 static void show(Activity a,String title,String episode,Object media,Runnable restart,Runnable full){Dialog d=new Dialog(a);d.requestWindowFeature(Window.FEATURE_NO_TITLE);LinearLayout row=new LinearLayout(a);row.setPadding(dp(a,24),dp(a,24),dp(a,24),dp(a,24));row.setBackground(PreviewDialog.surface(a,false));LinearLayout text=new LinearLayout(a);text.setOrientation(android.widget.LinearLayout.VERTICAL);row.addView(text,new LinearLayout.LayoutParams(0,-2,1));label(text,title,24);if(!episode.isEmpty())label(text,episode,13);
  if(media instanceof Video){Video v=(Video)media;boolean same=v instanceof Episode?title.equals(((Episode)v).getShowName()):title.equals(v.getName());if(same){String meta=(v instanceof Movie&&((Movie)v).getYear()>0?((Movie)v).getYear()+"  ·  ":"")+(v.getDurationMs()>0?v.getDurationMs()/60000+" min":"");label(text,meta,12);label(text,v.getDescriptionBody(),14);java.util.concurrent.ExecutorService metadata=java.util.concurrent.Executors.newSingleThreadExecutor();metadata.execute(()->{try{com.archos.mediascraper.BaseTags tags=v.getFullScraperTags(a.getApplicationContext());if(tags!=null)text.post(()->{if(!d.isShowing())return;String director=tags.getDirectorsFormatted(),writers=tags.getWritersFormatted();StringBuilder subset=new StringBuilder(),complete=new StringBuilder();if(director!=null&&!director.isEmpty()){label(text,"Director  ·  "+director,12);complete.append("Director · ").append(director).append("\n\n");}if(writers!=null&&!writers.isEmpty())complete.append("Writers · ").append(writers).append("\n\n");int count=0;for(java.util.Map.Entry<String,String> person:tags.getActors().entrySet()){String line=person.getKey()+(person.getValue()==null||person.getValue().isEmpty()?"":" · "+person.getValue());complete.append(line).append("\n");if(count++<3)subset.append(line).append("\n");}if(subset.length()>0)label(text,"Cast & Crew\n"+subset,12);if(complete.length()>0){TextView all=new TextView(a);all.setText("See All Cast & Crew");all.setTextColor(-1);all.setTextSize(13);all.setPadding(dp(a,10),dp(a,8),dp(a,10),dp(a,8));all.setFocusable(true);all.setBackground(PreviewDialog.buttonFocus(a));all.setOnClickListener(vw->PreviewDialog.read(a,"Cast & Crew",complete.toString()));text.addView(all);}});}catch(Exception unavailable){/* Existing local metadata is optional. */}finally{metadata.shutdown();}});}}
  LinearLayout actions=new LinearLayout(a);actions.setOrientation(android.widget.LinearLayout.VERTICAL);actions.setPadding(dp(a,6),dp(a,6),dp(a,6),dp(a,6));actions.setBackground(PreviewDialog.surface(a,false));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(dp(a,210),-2);lp.leftMargin=dp(a,28);row.addView(actions,lp);
  String[] labels={"Resume","Play from beginning","File and technical details"};for(int i=0;i<labels.length;i++){final int index=i;TextView b=new TextView(a);b.setText(labels[i]);b.setTextColor(-1);b.setTextSize(13);b.setPadding(dp(a,10),0,dp(a,10),0);b.setGravity(Gravity.CENTER_VERTICAL);PreviewIcon.apply(b,labels[i],17);b.setBackground(PreviewDialog.focus(a));b.setFocusable(i<3);b.setEnabled(i<3);if(i==3)b.setAlpha(.4f);b.setOnClickListener(v->{d.dismiss();if(index==1)restart.run();if(index==2)full.run();});actions.addView(b,new LinearLayout.LayoutParams(-1,dp(a,38)));}
  ScrollView content=new ScrollView(a);content.setFillViewport(false);content.addView(row);d.setContentView(content);d.show();d.getWindow().setBackgroundDrawableResource(android.R.color.transparent);d.getWindow().setDimAmount(.18f);int width=Math.min(dp(a,840),a.getResources().getDisplayMetrics().widthPixels-dp(a,64)),height=Math.min(dp(a,360),a.getResources().getDisplayMetrics().heightPixels-dp(a,96));content.measure(View.MeasureSpec.makeMeasureSpec(width,View.MeasureSpec.EXACTLY),View.MeasureSpec.makeMeasureSpec(height,View.MeasureSpec.AT_MOST));d.getWindow().setLayout(width,Math.min(height,content.getMeasuredHeight()));d.getWindow().setGravity(Gravity.CENTER);actions.getChildAt(0).requestFocus();
 }
 private static int dp(Activity a,int v){return PreviewDialog.dp(a,v);}private static void label(LinearLayout p,String s,int size){if(s==null||s.isEmpty())return;TextView t=new TextView(p.getContext());t.setText(s);t.setTextSize(size);t.setTextColor(size>=19?-1:0xffbfd1de);t.setShadowLayer(3f,0f,1f,android.graphics.Color.BLACK);t.setMaxLines(size>=19||size==12?2:4);t.setEllipsize(android.text.TextUtils.TruncateAt.END);t.setPadding(0,0,0,PreviewDialog.dp(p.getContext(),10));p.addView(t);}
}
