package com.archos.mediacenter.video.leanback.settings;
import android.view.*;
import android.widget.*;
import androidx.preference.*;
import java.util.*;
import com.archos.mediacenter.video.R;
import com.archos.mediacenter.video.leanback.PreviewIcon;
import com.archos.mediacenter.video.leanback.PreviewDialog;
import com.archos.mediacenter.video.leanback.PreviewHomeRows;
import com.archos.mediacenter.video.leanback.PreviewAccent;
public final class PreviewSettings {
 private static final java.util.WeakHashMap<android.content.Context,TextView> HELP=new java.util.WeakHashMap<>();
 private static final String[] ORIGINAL_NAMES={"General","Home & Discovery","Playback","Video & Audio","Subtitles","Library","Sources & Storage","Appearance","Trakt","Streaming","Integrations","Advanced","About","Legacy"};
 public static void organise(PreferenceFragmentCompat fragment){
  PreferenceScreen root=fragment.getPreferenceScreen();if(root==null)return;
  Map<String,PreferenceCategory> categories=new LinkedHashMap<>();
  String[] keys={"preferences_about","category_leanback_user_interface","preview_playback","preferences_category_video","preview_subtitles","scraper_category","netshare_category","category_user_interface","trakt_category","streaming_category","preview_integrations","preferences_category_advanced_video","about_category","preview_legacy"};
  for(int i=0;i<keys.length;i++){Preference p=root.findPreference(keys[i]);PreferenceCategory c=p instanceof PreferenceCategory?(PreferenceCategory)p:new PreferenceCategory(fragment.requireContext());if(p==null){c.setKey(keys[i]);root.addPreference(c);}c.setTitle(ORIGINAL_NAMES[i]);c.setOrder(i*100);categories.put(ORIGINAL_NAMES[i],c);}
  java.util.List<PreferenceCategory> old=new ArrayList<>();for(int i=0;i<root.getPreferenceCount();i++)if(root.getPreference(i) instanceof PreferenceCategory)old.add((PreferenceCategory)root.getPreference(i));
  for(PreferenceCategory c:old){String title=String.valueOf(c.getTitle()).toLowerCase(Locale.ROOT);if(!categories.containsValue(c)){PreferenceCategory dest=categories.get(title.contains("language")?"Subtitles":title.contains("torrent")?"Advanced":"Sources & Storage");while(c.getPreferenceCount()>0){Preference p=c.getPreference(0);c.removePreference(p);dest.addPreference(p);}c.setVisible(false);}}
  move(root,categories.get("Appearance"),"ui_lang");move(root,categories.get("About"),"preferences_version");
  for(String key:new String[]{"playback_speed","audio_speed_audiotrack","resume","repeat_mode","playback_repeat_mode"})move(root,categories.get("Playback"),key);
  if(root.findPreference("remember_library_views")==null){SwitchPreferenceCompat remember=new SwitchPreferenceCompat(fragment.requireContext());remember.setKey("remember_library_views");remember.setTitle("Remember library view preferences");remember.setSummary("Keep Movies and TV Shows views, filters, sort and order separately");remember.setDefaultValue(true);categories.get("Library").addPreference(remember);}
  for(String key:new String[]{"subtitles_credentials","subtitles_hide_default","favSubLang","languages_list","codepage"})move(root,categories.get("Subtitles"),key);
  for(String key:new String[]{"display_resume_box","hide_controls_on_pause","player_projector_mode_key"})move(root,categories.get("Playback"),key);
  move(root,categories.get("Library"),"rescan_storage");
  Preference fullScan=root.findPreference("rescan_storage");if(fullScan!=null){fullScan.setTitle("Full Library Scan");fullScan.setSummary("Scan local storage and indexed network folders; retry unmatched descriptions");}
  SwitchPreferenceCompat automatic=new SwitchPreferenceCompat(fragment.requireContext());automatic.setKey("auto_rescan_on_app_restart");automatic.setTitle("Scan network library on return");automatic.setSummary("Check indexed sources, including WebDAV, when Supernova opens or returns to the foreground");automatic.setDefaultValue(true);categories.get("Library").addPreference(automatic);
  ListPreference interval=new ListPreference(fragment.requireContext());interval.setKey("preview_scan_interval_control");interval.setPersistent(false);interval.setTitle("Automatic network scan interval");interval.setEntries(new String[]{"Off","15 minutes","30 minutes","1 hour","6 hours","24 hours"});interval.setEntryValues(new String[]{"0","900000","1800000","3600000","21600000","86400000"});int savedPeriod=com.archos.mediaprovider.video.NetworkAutoRefresh.getRescanPeriod(fragment.requireContext());interval.setValue(String.valueOf(savedPeriod));interval.setSummaryProvider(p->{int period=com.archos.mediaprovider.video.NetworkAutoRefresh.getRescanPeriod(fragment.requireContext());return period<=0?"Off":period/60000+" minutes · Android may defer background jobs";});interval.setOnPreferenceChangeListener((p,value)->{com.archos.mediaprovider.video.NetworkScannerUtil.scheduleNewRescan(fragment.requireContext(),0,Integer.parseInt(value.toString()),true);return true;});categories.get("Library").addPreference(interval);
  // Only the inert UI placeholder is removed. No updater or saved preference existed.
  Preference updates=root.findPreference("preview_updates");if(updates!=null&&updates.getParent()!=null)updates.getParent().removePreference(updates);
  // Existing torrent preferences own working onClick handlers and retain their folder picker.
  for(String key:new String[]{"preferences_video_os","preferences_video_tmdb","preferences_video_trakt"}){Preference attribution=root.findPreference(key);if(attribution!=null){attribution.setEnabled(false);attribution.setSelectable(false);}}
  for(String key:new String[]{"always_leanback_on_tv_key","reset_last_played_row","reset_last_played_section","preferences_movie_sort_order","preferences_tv_show_sort_order","preferences_animes_sort_order","try_new_ui","smart_recently_rows","separate_anime_movie_show","show_last_added_row","show_last_played_row","show_watching_up_next_row","show_all_movies_row","show_all_tv_shows_row","show_all_animes_row","show_documentaries","hide_trailer_row","show_by_rating","app_theme"}){
   Preference p=root.findPreference(key);if(p!=null){move(root,categories.get("Legacy"),key);p.setEnabled(false);p.setSelectable(false);p.setSummary(key.equals("player_projector_mode_key")?"Legacy: aligns video and effects to the top of the screen. Existing value is preserved; presentation control retired pending device QA.":key.equals("app_theme")?"Legacy theme retained for classic surfaces. Use Accent & Colour in Appearance.":"Deprecated in this interface — underlying behaviour and saved value preserved");}
  }
  Preference accent=new Preference(fragment.requireContext());accent.setKey("preview_accent_picker");accent.setTitle("Accent & Colour");accent.setSummary("Focus, selected controls and subtle utility gradients");accent.setOnPreferenceClickListener(p->{PreviewAccent.choose(fragment.requireContext(),()->fragment.requireActivity().recreate());return true;});categories.get("Appearance").addPreference(accent);
  Preference rows=new Preference(fragment.requireContext());rows.setKey("preview_home_editor");rows.setTitle("Home rows");rows.setSummary("Create, rename, hide and reorder rows; manage Watch Next");rows.setOnPreferenceClickListener(p->{PreviewHomeRows.customise(fragment.requireContext(),()->{});return true;});categories.get("Home & Discovery").addPreference(rows);
  Preference clear=new Preference(fragment.requireContext());clear.setKey("preview_clear_watch_next");clear.setTitle("Clear Watch Next");clear.setSummary("Remove all Watch Next titles after confirmation. Library and playback history are kept.");clear.setOnPreferenceClickListener(p->{PreviewHomeRows.clearWatchNext(fragment.requireContext());return true;});categories.get("Home & Discovery").addPreference(clear);
  String[] sources={"recent","trending","popular"},sourceNames={"Featured: Recently Added","Featured: Trakt Trending","Featured: Trakt Popular"};for(int n=0;n<sources.length;n++){SwitchPreferenceCompat enabled=new SwitchPreferenceCompat(fragment.requireContext());enabled.setKey("preview_featured_"+sources[n]);enabled.setTitle(sourceNames[n]);enabled.setSummary("Select from matching local-library titles; offline local fallback");enabled.setDefaultValue(true);categories.get("Home & Discovery").addPreference(enabled);}
  SwitchPreferenceCompat diagnostics=new SwitchPreferenceCompat(fragment.requireContext());diagnostics.setKey(com.archos.mediacenter.video.diagnostics.Diagnostics.KEY);diagnostics.setTitle("Diagnostic Logging");diagnostics.setSummary("Off by default. Bounded, privacy-filtered logs for development and Shield QA.");diagnostics.setDefaultValue(false);diagnostics.setOnPreferenceChangeListener((p,value)->{com.archos.mediacenter.video.diagnostics.Diagnostics.setEnabled(fragment.requireContext(),(Boolean)value);return true;});categories.get("Advanced").addPreference(diagnostics);
  Preference export=new Preference(fragment.requireContext());export.setKey("export_diagnostic_report");export.setTitle("Export Diagnostic Report");export.setSummary("Save recent logs and safe device/build information as a ZIP. Choose a destination using Android Files.");export.setOnPreferenceClickListener(p->{fragment.startActivity(new android.content.Intent(fragment.requireContext(),com.archos.mediacenter.video.diagnostics.DiagnosticExportActivity.class));return true;});categories.get("Advanced").addPreference(export);
  PreviewBuildInfo.install(fragment,categories.get("About"));
  consolidate(fragment,root,categories);
  auditPresentation(root);
  style(root);

 }
 private static final String[] NAMES={"Playback","Video","Audio","Subtitles","Library & Metadata","Home","Appearance","Streaming","Network","Integrations","Advanced","About"};
 private static boolean oneOf(String key,String values){return Arrays.asList(values.split(",")).contains(key);}
 private static void consolidate(PreferenceFragmentCompat fragment,PreferenceScreen root,Map<String,PreferenceCategory> categories){
  Map<String,PreferenceCategory> destinations=new LinkedHashMap<>();
  for(String name:NAMES){PreferenceCategory category=new PreferenceCategory(fragment.requireContext());category.setKey("preview414_"+name.toLowerCase(Locale.ROOT).replaceAll("[^a-z]","_"));category.setTitle(name);category.setOrder(10000+destinations.size());destinations.put(name,category);}
  List<Preference> preferences=new ArrayList<>();Map<Preference,String> origin=new IdentityHashMap<>();
  for(Map.Entry<String,PreferenceCategory> entry:categories.entrySet()){PreferenceCategory category=entry.getValue();while(category.getPreferenceCount()>0){Preference pref=category.getPreference(0);origin.put(pref,entry.getKey());preferences.add(pref);category.removePreference(pref);}category.setVisible(false);}
  for(PreferenceCategory category:destinations.values())root.addPreference(category);
  PreferenceCategory trakt=new PreferenceCategory(fragment.requireContext());trakt.setTitle("Trakt");trakt.setKey("preview414_trakt");destinations.get("Integrations").addPreference(trakt);
  PreferenceCategory subtitles=new PreferenceCategory(fragment.requireContext());subtitles.setTitle("OpenSubtitles");subtitles.setKey("preview414_opensubtitles");destinations.get("Integrations").addPreference(subtitles);
  PreferenceCategory intro=new PreferenceCategory(fragment.requireContext());intro.setTitle("IntroDB");intro.setKey("preview414_introdb");destinations.get("Integrations").addPreference(intro);
  Map<String,PreferenceCategory> advanced=new LinkedHashMap<>();
  for(String name:new String[]{"Video Compatibility","Audio Compatibility","Network Compatibility","Streaming Compatibility","Subtitle Compatibility","Diagnostics"}){PreferenceCategory group=new PreferenceCategory(fragment.requireContext());group.setTitle(name);group.setKey("preview414_"+name.replace(' ','_'));destinations.get("Advanced").addPreference(group);advanced.put(name,group);}
  for(Preference pref:preferences){String key=String.valueOf(pref.getKey()),old=origin.get(pref);String target="Library & Metadata";PreferenceCategory group=null;
   if(old.equals("Legacy")||oneOf(key,"uimode,uimode_leanback,preferences_torrent_path,preferences_torrent_blocklist,share_folders,rescan_storage,auto_rescan_on_app_restart,preview_scan_interval_control")){pref.setVisible(false);target="Advanced";}
   else if(key.startsWith("trakt_"))group=trakt;
   else if(key.equals("subtitles_credentials"))group=subtitles;
   else if(old.equals("About"))target="About";
   else if(old.equals("Streaming"))target="Streaming";
   else if(old.equals("Home & Discovery"))target="Home";
   else if(oneOf(key,"ui_lang,ui_zoom,preview_accent_picker"))target="Appearance";
   else if(oneOf(key,"enable_tv_refreshrate_switch_mode,dolby_vision_mode,activate_tv_switch"))target="Video";
   else if(oneOf(key,"favAudioLang,prefer_original_audio_track,force_audio_passthrough_multiple,player_spatialization_enabled"))target="Audio";
   else if(oneOf(key,"favSubLang,languages_list,subtitles_hide_default"))target="Subtitles";
   else if(key.equals("codepage"))group=advanced.get("Subtitle Compatibility");
   else if(oneOf(key,"force_software_decoding,dec_choice,enable_cutout_mode_short_edges,enable_cutout_both_sidesx,parser_sync_mode"))group=advanced.get("Video Compatibility");
   else if(oneOf(key,"audio_interface_choice,audio_decoder_choice,force_passthrough,audio_speed_audiotrack,enable_dynamic_audio_delay,disable_downmix,enable_downmix_androidtv"))group=advanced.get("Audio Compatibility");
   else if(key.startsWith("pref_smb")||key.equals("pref_sshj"))group=advanced.get("Network Compatibility");
   else if(oneOf(key,"stream_buffer_size,stream_max_iframe_size"))group=advanced.get("Streaming Compatibility");
   else if(oneOf(key,"supernova_diagnostic_logging,export_diagnostic_report"))group=advanced.get("Diagnostics");
   else if(oneOf(key,"playback_speed,display_resume_box,hide_controls_on_pause,player_projector_mode_key,allow_3rd_party_player,network_bookmarks")||key.equals(fragment.getString(R.string.reset_brightness_on_start_key)))target="Playback";
   else if(key.equals("pref_network_prefer_vpn")||key.equals(fragment.getString(R.string.preferences_network_mobile_vpn_key)))target="Network";
   else if(old.equals("Advanced"))target="Advanced";
   (group==null?destinations.get(target):group).addPreference(pref);
  }
  SwitchPreferenceCompat skip=new SwitchPreferenceCompat(fragment.requireContext());skip.setKey(com.archos.mediacenter.video.player.PlayerService.KEY_INTRODB_ENABLED);skip.setTitle("Automatic segment skipping");skip.setSummary("Use IntroDB segments during playback; recaps follow the existing binge-mode behaviour.");skip.setDefaultValue(com.archos.mediacenter.video.player.PlayerService.DEFAULT_INTRODB_ENABLED);intro.addPreference(skip);
  Preference hidden=root.findPreference("subtitles_hide_default");
  if(hidden instanceof TwoStatePreference){TwoStatePreference original=(TwoStatePreference)hidden;original.setVisible(false);SwitchPreferenceCompat positive=new SwitchPreferenceCompat(fragment.requireContext());positive.setKey("preview_subtitles_default");positive.setPersistent(false);positive.setTitle("Subtitles by Default");positive.setChecked(!original.isChecked());positive.setEnabled(original.isEnabled());positive.setOnPreferenceChangeListener((pref,value)->{boolean hide=!(Boolean)value;if(!original.callChangeListener(hide))return false;original.setChecked(hide);return true;});destinations.get("Subtitles").addPreference(positive);}
 }
 private static String contextFor(Preference p){String text=String.valueOf(p.getTitle())+"\n\n"+(p.getSummary()==null?"Select to change this setting.":p.getSummary());
  if(p instanceof ListPreference){ListPreference list=(ListPreference)p;CharSequence[] entries=list.getEntries(),values=list.getEntryValues();if(entries!=null&&values!=null){text+="\n";for(int i=0;i<Math.min(entries.length,6);i++)text+="\n"+(values[i].toString().equals(list.getValue())?"●  ":"○  ")+entries[i];}}
  else if(p instanceof TwoStatePreference)text+="\n\nCurrent value: "+(((TwoStatePreference)p).isChecked()?"On":"Off");
  if(String.valueOf(p.getKey()).toLowerCase(Locale.ROOT).contains("sub"))text+="\n\nSubtitle preview\nThe next chapter begins.";
  return text;
 }
 private static void focusFirst(androidx.recyclerview.widget.RecyclerView list){list.post(new Runnable(){int attempts;public void run(){if(!list.isAttachedToWindow())return;if(list.hasPendingAdapterUpdates()){if(attempts++<16)list.postOnAnimation(this);return;}for(int i=0;i<list.getChildCount();i++){View child=list.getChildAt(i);if(child.isFocusable()&&child.isEnabled()&&child.requestFocus())return;}if(attempts++<16)list.postOnAnimation(this);}});}
 public static void auditPresentation(PreferenceGroup root){
  for(String key:new String[]{"smart_recently_rows","separate_anime_movie_show","show_last_added_row","show_last_played_row","show_watching_up_next_row","show_all_movies_row","show_all_tv_shows_row","show_all_animes_row","show_documentaries","hide_trailer_row","show_by_rating"}){Preference pref=root.findPreference(key);if(pref!=null){pref.setEnabled(false);pref.setSelectable(false);pref.setSummary("Legacy interface only — saved value preserved");}}
  style(root);
 }
 public static void style(PreferenceGroup group){for(int i=0;i<group.getPreferenceCount();i++){Preference p=group.getPreference(i);p.setIconSpaceReserved(false);p.setLayoutResource(p instanceof PreferenceCategory?R.layout.preview_preference_category:R.layout.preview_preference);if(!(p instanceof PreferenceCategory)){PreviewIcon icon=new PreviewIcon(String.valueOf(p.getTitle()));int[] colours={0xff65cffa,0xffb999f1,0xff67dca5,0xffffcc79};icon.setColorFilter(new android.graphics.PorterDuffColorFilter(colours[Math.floorMod(String.valueOf(p.getKey()).hashCode(),colours.length)],android.graphics.PorterDuff.Mode.SRC_IN));icon.setColorFilter(new android.graphics.PorterDuffColorFilter(PreviewAccent.color(group.getContext()),android.graphics.PorterDuff.Mode.SRC_IN));p.setIcon(icon);}if(p instanceof CheckBoxPreference)p.setWidgetLayoutResource(R.layout.preview_preference_checkbox);if(p instanceof PreferenceGroup)style((PreferenceGroup)p);}}
 // Intentional extension of the pinned AndroidX 1.2.1 preference adapter to preserve native preference semantics. Recheck on AndroidX upgrades.
 @android.annotation.SuppressLint("RestrictedApi")
 public static androidx.recyclerview.widget.RecyclerView.Adapter<?> adapter(PreferenceScreen root){return new PreferenceGroupAdapter(root){@Override public void onBindViewHolder(PreferenceViewHolder holder,int position){super.onBindViewHolder(holder,position);Preference p=getItem(position);boolean category=p instanceof PreferenceCategory;holder.itemView.setBackgroundColor(category?android.graphics.Color.TRANSPARENT:0x280e2332);holder.itemView.setOnFocusChangeListener((v,focused)->{if(focused){TextView help=HELP.get(activityContext(v.getContext()));if(help!=null)help.setText(contextFor(p));}});holder.itemView.setForeground(category?null:PreviewDialog.focus(holder.itemView.getContext()));holder.itemView.setFocusable(!category&&p.isEnabled()&&p.isSelectable());holder.itemView.setFocusableInTouchMode(!category&&p.isEnabled()&&p.isSelectable());if(holder.itemView.hasFocus()){TextView help=HELP.get(activityContext(holder.itemView.getContext()));if(help!=null)help.setText(contextFor(p));}holder.itemView.setAlpha(category||p.isEnabled()?1f:.38f);androidx.recyclerview.widget.RecyclerView.LayoutParams lp=new androidx.recyclerview.widget.RecyclerView.LayoutParams(-1,category?-2:PreviewDialog.dp(holder.itemView.getContext(),54));lp.setMargins(0,0,PreviewDialog.dp(holder.itemView.getContext(),0),PreviewDialog.dp(holder.itemView.getContext(),4));holder.itemView.setLayoutParams(lp);android.view.View widget=holder.findViewById(android.R.id.widget_frame);if(widget!=null&&!(p instanceof androidx.preference.TwoStatePreference)){android.view.ViewGroup.LayoutParams wp=widget.getLayoutParams();wp.width=PreviewDialog.dp(holder.itemView.getContext(),48);wp.height=PreviewDialog.dp(holder.itemView.getContext(),30);widget.setLayoutParams(wp);fitBadge(widget);}tintSwitches(holder.itemView);holder.setDividerAllowedAbove(false);holder.setDividerAllowedBelow(false);}};}
 // Intentional extension of the pinned AndroidX 1.2.1 preference adapter to preserve native preference semantics. Recheck on AndroidX upgrades.
 @android.annotation.SuppressLint("RestrictedApi")
 public static androidx.recyclerview.widget.RecyclerView grid(android.content.Context c){
  com.archos.mediacenter.video.leanback.PreviewFocusRecycler list=new com.archos.mediacenter.video.leanback.PreviewFocusRecycler(c){
   @Override protected boolean focusablePosition(int p){if(!(getAdapter() instanceof PreferenceGroupAdapter))return false;Preference item=((PreferenceGroupAdapter)getAdapter()).getItem(p);return item!=null&&!(item instanceof PreferenceCategory)&&item.isEnabled()&&item.isSelectable();}
   @Override public View focusSearch(View focused,int direction){View item=findContainingItemView(focused);int pos=item==null?-1:getChildAdapterPosition(item);androidx.recyclerview.widget.GridLayoutManager lm=(androidx.recyclerview.widget.GridLayoutManager)getLayoutManager();if(direction==View.FOCUS_LEFT&&pos>=0&&lm.getSpanSizeLookup().getSpanIndex(pos,1)==0&&getTag() instanceof View)return (View)getTag();return super.focusSearch(focused,direction);}
  };
  androidx.recyclerview.widget.GridLayoutManager layout=new androidx.recyclerview.widget.GridLayoutManager(c,1);layout.setSpanSizeLookup(new androidx.recyclerview.widget.GridLayoutManager.SpanSizeLookup(){public int getSpanSize(int position){if(!(list.getAdapter() instanceof PreferenceGroupAdapter))return 1;return ((PreferenceGroupAdapter)list.getAdapter()).getItem(position) instanceof PreferenceCategory?1:1;}});list.setLayoutManager(layout);list.setClipToPadding(false);return list;
 }
 private static void tintSwitches(View view){int colour=PreviewAccent.color(view.getContext());android.content.res.ColorStateList tint=new android.content.res.ColorStateList(new int[][]{new int[]{android.R.attr.state_checked},new int[]{}},new int[]{colour,0xff738493});if(view instanceof androidx.appcompat.widget.SwitchCompat){((androidx.appcompat.widget.SwitchCompat)view).setThumbTintList(tint);((androidx.appcompat.widget.SwitchCompat)view).setTrackTintList(tint.withAlpha(90));}else if(view instanceof android.widget.CompoundButton)((android.widget.CompoundButton)view).setButtonTintList(tint);if(view instanceof ViewGroup)for(int i=0;i<((ViewGroup)view).getChildCount();i++)tintSwitches(((ViewGroup)view).getChildAt(i));}
 private static void fitBadge(View view){if(view instanceof ImageView){ImageView image=(ImageView)view;image.setScaleType(ImageView.ScaleType.FIT_CENTER);ViewGroup.LayoutParams size=image.getLayoutParams();size.width=ViewGroup.LayoutParams.MATCH_PARENT;size.height=ViewGroup.LayoutParams.MATCH_PARENT;image.setLayoutParams(size);}else if(view instanceof ViewGroup){ViewGroup group=(ViewGroup)view;for(int i=0;i<group.getChildCount();i++)fitBadge(group.getChildAt(i));}}
 private static void move(PreferenceScreen root,PreferenceCategory dest,String key){Preference p=root.findPreference(key);if(p==null||p.getParent()==dest)return;PreferenceGroup parent=p.getParent();if(parent!=null)parent.removePreference(p);dest.addPreference(p);}
 public static void sidebar(PreferenceFragmentCompat fragment){
  androidx.recyclerview.widget.RecyclerView list=fragment.getListView();ViewGroup parent=(ViewGroup)list.getParent();int index=parent.indexOfChild(list);ViewGroup.LayoutParams original=list.getLayoutParams();parent.removeView(list);
  LinearLayout split=new LinearLayout(fragment.requireContext());split.setPadding(0,dp(fragment,12),0,0);split.setBackgroundColor(android.graphics.Color.TRANSPARENT);ScrollView scroll=new ScrollView(fragment.requireContext());scroll.setVerticalScrollBarEnabled(false);LinearLayout links=new LinearLayout(fragment.requireContext());links.setOrientation(android.widget.LinearLayout.VERTICAL);scroll.addView(links);LinearLayout.LayoutParams rail=new LinearLayout.LayoutParams(0,-1,.20f);rail.rightMargin=dp(fragment,12);scroll.setBackground(PreviewDialog.surface(fragment.requireContext(),false));split.addView(scroll,rail);list.setBackground(PreviewDialog.surface(fragment.requireContext(),false));split.addView(list,new LinearLayout.LayoutParams(0,-1,.46f));ScrollView helpScroll=new ScrollView(fragment.requireContext());TextView help=new TextView(fragment.requireContext());help.setText("Settings\n\nSelect a category to review your saved preferences. Playback, library and source settings remain available.");help.setTextSize(14);help.setTextColor(0xffb4cbe0);help.setLineSpacing(dp(fragment,4),1);help.setPadding(dp(fragment,20),dp(fragment,12),dp(fragment,12),dp(fragment,12));helpScroll.addView(help);helpScroll.setBackground(PreviewDialog.surface(fragment.requireContext(),false));helpScroll.setFocusable(false);helpScroll.setDescendantFocusability(ViewGroup.FOCUS_BLOCK_DESCENDANTS);LinearLayout.LayoutParams helpSize=new LinearLayout.LayoutParams(0,-1,.34f);helpSize.leftMargin=dp(fragment,12);split.addView(helpScroll,helpSize);HELP.put(activityContext(fragment.requireContext()),help);parent.addView(split,index,original);
  PreferenceScreen root=fragment.getPreferenceScreen();final TextView[] selected={null};android.content.SharedPreferences state=PreferenceManager.getDefaultSharedPreferences(fragment.requireContext());String requested=fragment.requireActivity().getIntent().getBooleanExtra("show_streaming_settings",false)?"Streaming":state.getString("preview_settings_category","Playback");fragment.requireActivity().getIntent().removeExtra("show_streaming_settings");TextView initial=null;
  for(String name:NAMES){PreferenceCategory target=null;for(int i=0;i<root.getPreferenceCount();i++){Preference p=root.getPreference(i);if(p instanceof PreferenceCategory&&((PreferenceCategory)p).getPreferenceCount()>0&&name.contentEquals(p.getTitle())){target=(PreferenceCategory)p;break;}}if(target==null||target.getPreferenceCount()==0)continue;final PreferenceCategory category=target;
   TextView button=new TextView(fragment.requireContext());button.setText(name);button.setTextSize(13);button.setTextColor(0xffb4cbe0);button.setGravity(Gravity.CENTER_VERTICAL);button.setPadding(dp(fragment,10),0,dp(fragment,10),0);PreviewIcon.apply(button,name,17);button.setFocusable(true);button.setFocusableInTouchMode(true);button.setBackground(PreviewDialog.focus(fragment.requireContext()));
   Runnable select=()->{if(selected[0]==button)return;if(selected[0]!=null)selected[0].setTextColor(0xffb4cbe0);selected[0]=button;button.setTextColor(PreviewAccent.color(fragment.requireContext()));list.setTag(button);for(int k=0;k<root.getPreferenceCount();k++){Preference pref=root.getPreference(k);if(pref instanceof PreferenceCategory)pref.setVisible(pref==category);}state.edit().putString("preview_settings_category",name).apply();help.setText(name+"\n\n"+category.getPreferenceCount()+" settings\n\nMove right to review each setting. Saved values apply immediately unless a setting says otherwise.");list.scrollToPosition(0);};
   button.setOnFocusChangeListener((v,focused)->{if(focused)select.run();});button.setOnClickListener(v->{select.run();focusFirst(list);});button.setOnKeyListener((v,key,event)->{if(key==KeyEvent.KEYCODE_DPAD_RIGHT&&event.getAction()==KeyEvent.ACTION_DOWN){focusFirst(list);return true;}return false;});links.addView(button,new LinearLayout.LayoutParams(-1,dp(fragment,40)));if(initial==null||name.equals(requested))initial=button;
  }
  if(initial!=null){TextView first=initial;first.post(()->{first.requestFocus();focusFirst(list);});}
 }
 private static android.content.Context activityContext(android.content.Context c){while(c instanceof android.content.ContextWrapper&&!(c instanceof android.app.Activity))c=((android.content.ContextWrapper)c).getBaseContext();return c;}
 private static int dp(PreferenceFragmentCompat f,int v){return Math.round(v*f.getResources().getDisplayMetrics().density);}
}
