package com.archos.mediacenter.video.leanback;

import android.app.Application;
import android.graphics.*;
import android.graphics.drawable.ColorDrawable;
import android.view.*;
import android.widget.*;
import androidx.recyclerview.widget.*;
import com.archos.mediacenter.video.browser.adapters.object.Movie;
import com.archos.mediacenter.video.leanback.PreviewLibraryLoader.*;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.robolectric.*;
import org.robolectric.annotation.*;
import static org.junit.Assert.*;

@RunWith(RobolectricTestRunner.class)
@Config(application=Application.class,sdk=28,qualifiers="w960dp-h540dp-land-mdpi")
@GraphicsMode(GraphicsMode.Mode.NATIVE)
public class PreviewHomeHotfixTest {
 private Snapshot source(){Snapshot s=new Snapshot();for(int id=1;id<=24;id++){Movie m=new Movie(id,"/fixture/"+id,"Film "+id,id,"A family discovers an unexpected path through a changing world.",2024,7,"12",null,100000,0,0,0,false,false,false,false,id,id,1920,1080,null,null,null,null,0,1,1000,0);s.movies.add(new Entry(m,id,0,"Drama"));}s.continuingMovies.addAll(s.movies.subList(0,12));s.recent.addAll(s.movies.subList(12,24));return s;}
 private void init(){try{com.squareup.picasso.Picasso.get();}catch(IllegalStateException e){com.squareup.picasso.Picasso.setSingletonInstance(new com.squareup.picasso.Picasso.Builder(RuntimeEnvironment.getApplication()).build());}}
 @Test public void homeViewportHasEqualNeighboursSixtyPercentTeaserAndNoBackgroundDuplicate()throws Exception{
  init();var host=Robolectric.buildActivity(TopNavigationTest.Host.class).setup().visible();try{
   PreviewPages pages=new PreviewPages(host.get(),(h,item)->{});TopNavigation nav=new TopNavigation(host.get(),pages,pages::setTab,pages::atTop);host.get().setContentView(nav);java.util.List<android.net.Uri> background=new java.util.ArrayList<>();pages.setArtworkListener(background::add);pages.setDiscovery(new PreviewDiscovery());Snapshot s=source();for(Entry e:s.recent)e.backdrop=android.net.Uri.parse("file:///fixture/backdrop"+e.key());pages.setSnapshot(s);for(int i=0;i<8;i++)PreviewPagesTest.layout(nav);
   View active=nav.findViewWithTag("semantic:featured.active");assertNotNull(active);View previous=nav.findViewWithTag("semantic:featured.previous"),next=nav.findViewWithTag("semantic:featured.next");int[] a=new int[2],p=new int[2],n=new int[2];active.getLocationOnScreen(a);previous.getLocationOnScreen(p);next.getLocationOnScreen(n);assertEquals(a[1],p[1]);assertEquals(a[1],n[1]);assertEquals(active.getHeight(),previous.getHeight());assertEquals(active.getHeight(),next.getHeight());assertTrue(a[1]>nav.navigationTextBottom());assertNull(nav.findViewWithTag("hero:play"));assertNotNull(nav.findViewWithTag("hero:info"));assertTrue(background.stream().allMatch(java.util.Objects::isNull));
   RecyclerView list=(RecyclerView)pages.getChildAt(0);GridLayoutManager layout=(GridLayoutManager)list.getLayoutManager();ViewGroup row=(ViewGroup)layout.findViewByPosition(2);assertNotNull(row);RecyclerView rail=(RecyclerView)row.getChildAt(0);View card=rail.findViewHolderForAdapterPosition(0).itemView;int[] cardAt=new int[2];card.getLocationOnScreen(cardAt);float visible=(540-cardAt[1])/(float)card.getHeight();assertTrue("Artwork teaser 55–65%, got "+visible,visible>=.55f&&visible<=.65f);View second=layout.findViewByPosition(3);if(second!=null){int[] at=new int[2];second.getLocationOnScreen(at);assertTrue("No second ordinary row visible",at[1]>=540);}assertFalse(row.getClipChildren());assertFalse(rail.getClipChildren());int[] railAt=new int[2];rail.getLocationOnScreen(railAt);assertEquals(0,railAt[0]);assertEquals(960,rail.getWidth());
   paintArtwork(nav);PreviewPagesTest.capture(nav,"home-hotfix-initial");
  }finally{host.pause().stop().destroy();}
 }
 @Test public void variableLogoProportionsKeepStableMetadataAndSingleAction()throws Exception{
  init();var host=Robolectric.buildActivity(TopNavigationTest.Host.class).setup().visible();try{Snapshot s=source();s.movies.add(new Entry(new com.archos.mediacenter.video.browser.adapters.object.Tvshow(99,"TV fixture",null,2,10,0,"/show"),99,99,"Drama"));int baseline=-1;for(int[] dimensions:new int[][]{{320,35},{70,85},{140,60}}){PreviewFeaturedCard card=new PreviewFeaturedCard(host.get(),s.movies,dimensions[0]==70?s.movies.size()-1:0,()->{});host.get().setContentView(card);TextView title=card.findViewWithTag("semantic:featured.title");Bitmap logoBitmap=Bitmap.createBitmap(dimensions[0],dimensions[1],Bitmap.Config.ARGB_8888);logoBitmap.eraseColor(Color.WHITE);android.graphics.drawable.Drawable logo=(android.graphics.drawable.Drawable)org.robolectric.util.ReflectionHelpers.callConstructor(Class.forName("com.archos.mediacenter.video.leanback.OfficialTitleArtwork$Logo"),org.robolectric.util.ReflectionHelpers.ClassParameter.from(Bitmap.class,logoBitmap));title.setForeground(logo);title.setTextColor(Color.TRANSPARENT);card.measure(View.MeasureSpec.makeMeasureSpec(904,View.MeasureSpec.EXACTLY),View.MeasureSpec.makeMeasureSpec(340,View.MeasureSpec.EXACTLY));card.layout(0,0,904,340);View meta=card.findViewWithTag("semantic:featured.metadata"),plot=card.findViewWithTag("semantic:featured.synopsis"),info=card.findViewWithTag("hero:info");assertEquals(86,title.getHeight());assertTrue(meta.getTop()-title.getBottom()>=24);assertTrue(plot.getTop()-meta.getBottom()>=12);assertTrue(info.getTop()>=0);if(baseline<0)baseline=meta.getTop();else assertEquals(baseline,meta.getTop());assertNull(card.findViewWithTag("hero:play"));PreviewPagesTest.capture(card,"home-hotfix-logo-"+dimensions[0]);}}finally{host.pause().stop().destroy();}
 }
 @Test public void controlsAreActualInlineRowSiblingsAndBackRightReturnExactCard()throws Exception{
  init();var host=Robolectric.buildActivity(TopNavigationTest.Host.class).setup().visible();try{PreviewPages pages=new PreviewPages(host.get(),(h,item)->{});host.get().setContentView(pages);pages.setDiscovery(new PreviewDiscovery());pages.setSnapshot(source());PreviewPagesTest.layout(pages);RecyclerView list=(RecyclerView)pages.getChildAt(0);GridLayoutManager lm=(GridLayoutManager)list.getLayoutManager();for(int rowPosition:new int[]{2,4})for(int close:new int[]{KeyEvent.KEYCODE_BACK,KeyEvent.KEYCODE_DPAD_RIGHT}){lm.scrollToPositionWithOffset(rowPosition,100);PreviewPagesTest.layout(pages);LinearLayout row=(LinearLayout)lm.findViewByPosition(rowPosition);RecyclerView rail=(RecyclerView)row.getChildAt(0);View opener=rail.findViewHolderForAdapterPosition(0).itemView;assertTrue(opener.requestFocus());pages.dispatchKeyEvent(new KeyEvent(KeyEvent.ACTION_DOWN,KeyEvent.KEYCODE_DPAD_LEFT));PreviewPagesTest.layout(pages);View controls=pages.findViewWithTag("semantic:home.row.controls"),move=pages.findViewWithTag("semantic:home.row.move"),hide=pages.findViewWithTag("semantic:home.row.hide");assertSame(row,controls.getParent());assertEquals(0f,controls.getElevation(),0f);assertNull(controls.getBackground());assertTrue(move.hasFocus());assertEquals(controls.getTop(),rail.getTop());assertTrue(controls.getRight()<=rail.getLeft());move.dispatchKeyEvent(new KeyEvent(KeyEvent.ACTION_DOWN,KeyEvent.KEYCODE_DPAD_DOWN));assertSame(hide,pages.findFocus());hide.dispatchKeyEvent(new KeyEvent(KeyEvent.ACTION_DOWN,KeyEvent.KEYCODE_DPAD_UP));assertSame(move,pages.findFocus());PreviewPagesTest.capture(pages,"home-hotfix-inline-"+rowPosition+"-"+close);pages.dispatchKeyEvent(new KeyEvent(KeyEvent.ACTION_DOWN,close));pages.dispatchKeyEvent(new KeyEvent(KeyEvent.ACTION_UP,close));PreviewPagesTest.layout(pages);assertNull(pages.findViewWithTag("semantic:home.row.controls"));assertSame(opener,pages.findFocus());}}finally{host.pause().stop().destroy();}
 }
 private void paintArtwork(View v){if(v instanceof ImageView)((ImageView)v).setImageDrawable(new android.graphics.drawable.GradientDrawable(android.graphics.drawable.GradientDrawable.Orientation.TL_BR,new int[]{0xff597c93,0xff253c54,0xff986842}));if(v instanceof ViewGroup)for(int i=0;i<((ViewGroup)v).getChildCount();i++)paintArtwork(((ViewGroup)v).getChildAt(i));}
 @Test public void ordinaryCardArtworkPaintsPastInsetWhileAcceptedUnitStaysAligned()throws Exception{
  init();var host=Robolectric.buildActivity(TopNavigationTest.Host.class).setup().visible();try{PreviewPages pages=new PreviewPages(host.get(),(h,item)->{});host.get().setContentView(pages);pages.setDiscovery(new PreviewDiscovery());pages.setSnapshot(source());PreviewPagesTest.layout(pages);RecyclerView list=(RecyclerView)pages.getChildAt(0);GridLayoutManager outer=(GridLayoutManager)list.getLayoutManager();outer.scrollToPositionWithOffset(2,100);PreviewPagesTest.layout(pages);RecyclerView rail=(RecyclerView)((ViewGroup)outer.findViewByPosition(2)).getChildAt(0);rail.scrollBy(90,0);PreviewPagesTest.layout(pages);for(int i=0;i<rail.getChildCount();i++){com.archos.mediacenter.video.leanback.presenter.PreviewCardPresenter.Card card=(com.archos.mediacenter.video.leanback.presenter.PreviewCardPresenter.Card)rail.getChildAt(i);card.image.setImageDrawable(new ColorDrawable(Color.MAGENTA));}View first=rail.findViewHolderForAdapterPosition(0).itemView;int[] at=new int[2];first.getLocationOnScreen(at);assertTrue(at[0]<28);Bitmap picture=Bitmap.createBitmap(960,540,Bitmap.Config.ARGB_8888);pages.draw(new Canvas(picture));assertEquals("Card artwork crosses old x=28 parent clip",Color.MAGENTA,picture.getPixel(10,at[1]+40));picture.recycle();PreviewPagesTest.capture(pages,"home-hotfix-physical-edge");for(int position:new int[]{0,5,11}){((LinearLayoutManager)rail.getLayoutManager()).scrollToPositionWithOffset(position,0);PreviewPagesTest.layout(pages);View item=rail.findViewHolderForAdapterPosition(position).itemView;assertTrue(item.requestFocus());Shadows.shadowOf(android.os.Looper.getMainLooper()).idleFor(java.time.Duration.ofMillis(200));assertEquals(1f,item.getScaleX(),.001f);View unit=((ViewGroup)item).getChildAt(0);assertEquals(1.08f,unit.getScaleX(),.001f);assertSame(unit,((com.archos.mediacenter.video.leanback.presenter.PreviewCardPresenter.Card)item).image.getParent());paintArtwork(rail);PreviewPagesTest.capture(pages,"home-hotfix-focus-position-"+position);if(position==11){pages.dispatchKeyEvent(new KeyEvent(KeyEvent.ACTION_DOWN,KeyEvent.KEYCODE_DPAD_RIGHT));assertSame(item,pages.findFocus());}}
  }finally{host.pause().stop().destroy();}
 }

 @Test public void hideKeepsLibraryAndLeavesValidFocusOnRemainingHomeRow(){
  init();var host=Robolectric.buildActivity(TopNavigationTest.Host.class).setup().visible();try{PreviewPages pages=new PreviewPages(host.get(),(h,item)->{});host.get().setContentView(pages);Snapshot s=source();pages.setDiscovery(new PreviewDiscovery());pages.setSnapshot(s);PreviewPagesTest.layout(pages);RecyclerView list=(RecyclerView)pages.getChildAt(0);GridLayoutManager lm=(GridLayoutManager)list.getLayoutManager();lm.scrollToPositionWithOffset(2,100);PreviewPagesTest.layout(pages);RecyclerView rail=(RecyclerView)((ViewGroup)lm.findViewByPosition(2)).getChildAt(0);rail.findViewHolderForAdapterPosition(0).itemView.requestFocus();pages.dispatchKeyEvent(new KeyEvent(KeyEvent.ACTION_DOWN,KeyEvent.KEYCODE_DPAD_LEFT));PreviewPagesTest.layout(pages);pages.findViewWithTag("semantic:home.row.hide").performClick();for(int i=0;i<6;i++)PreviewPagesTest.layout(pages);assertNull(pages.findViewWithTag("semantic:home.row.controls"));assertNotNull(pages.findFocus());assertTrue(pages.findFocus().isAttachedToWindow());assertEquals(24,s.movies.size());assertTrue(s.continuingMovies.size()>0);pages.dispatchKeyEvent(new KeyEvent(KeyEvent.ACTION_DOWN,KeyEvent.KEYCODE_DPAD_RIGHT));assertNotNull(pages.findFocus());}finally{host.pause().stop().destroy();}
 }

}
